version: '3.9'

services:
  app:
    build: .
    ports:
      - 8000:8000
    image: aderayevans/shark-api:production
    container_name: django_container_production
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod