version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: aderayevans/shark-api
    container_name: django_container_local
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.local
