version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    image: aderayevans/shark-api:latest
    container_name: django_container
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    container_name: nginx
    depends_on:
      - app