# Generated by Django 4.0.6 on 2022-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
